#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1
CONTAINER="${DOCKER_CONTAINER}"
ROOT_DIR="${DOCKER_DIR}"

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# # Run GrumPHP
# (cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | exec $(HOOK_COMMAND) "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")

# Run GrumPHP
(cd "./" && echo "${DIFF}" | docker exec -i `docker-compose ps -q ${CONTAINER}` bash -c "cd ${ROOT_DIR} && ./vendor/bin/grumphp git:commit-msg --git-user='$GIT_USER' --git-email='$GIT_EMAIL' $COMMIT_MSG_FILE")

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
  exit $RC;
fi

# Clean exit:
exit 0;
