#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

CONTAINER="${DOCKER_CONTAINER}"
ROOT_DIR="${DOCKER_DIR}"

# Fetch the GIT diff and format it as command input:
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)

# Run GrumPHP
(cd "./" && echo "${DIFF}" | docker exec -i `docker-compose ps -q ${CONTAINER}` /bin/bash -c "cd ${ROOT_DIR} && ./vendor/bin/grumphp git:pre-commit --ansi --skip-success-output")

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
  exit $RC;
fi

# Clean exit:
exit 0;
